name: restore
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.0.15
  animated_splash_screen: ^1.2.0
  file_picker: ^4.6.1
  pdfx: ^2.3.0
  pdf: ^3.8.4
  dio: ^4.0.6
  easy_permission_validator: ^4.0.0
  path_provider: ^2.0.11
  is_first_run: ^1.0.0
  flutter_launcher_icons: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  image_path_android: "images/restore.png"
  image_path_ios: "images/restore.png"
  android: true
  ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "images/restore.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "images/restore.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "images/restore.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "images/restore.png"


flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
