name: restore
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  shared_preferences: ^2.0.15
  animated_splash_screen: ^1.2.0
  font_awesome_flutter: ^10.1.0
  http: ^0.13.4
  file_picker: ^4.6.1
  provider: ^6.0.3
  pdf: ^3.8.1
  pdfx: ^2.0.1+2
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
